# Exploring Pandas

In [3]:
import pandas as pd

In [4]:
#reading a csv file
customer_data = pd.read_csv('CUSTOMER_DATA.csv',encoding = "ISO-8859-1")

In [12]:
customer_data.head()

,CustomerID,CustomerName,ContactName,Address,City,PostalCode,Country
0,1,Alfreds Futterkiste,Maria Anders,Obere Str. 57,Berlin,12209,Germany
1,2,Ana Trujillo Emparedados y helados,Ana Trujillo,Avda. de la Constitución 2222,México D.F.,05021,Mexico
2,3,Antonio Moreno Taquería,Antonio Moreno,Mataderos 2312,México D.F.,05023,Mexico
3,4,Around the Horn,Thomas Hardy,120 Hanover Sq.,London,WA1 1DP,UK
4,5,Berglunds snabbköp,Christina Berglund,Berguvsvägen 8,Luleå,S-958 22,Sweden

In [13]:
customer_data.tail()

,CustomerID,CustomerName,ContactName,Address,City,PostalCode,Country
86,87,Wartian Herkku,Pirkko Koskitalo,Torikatu 38,Oulu,90110,Finland
87,88,Wellington Importadora,Paula Parente,"Rua do Mercado, 12",Resende,08737-363,Brazil
88,89,White Clover Markets,Karl Jablonski,305 - 14th Ave. S. Suite 3B,Seattle,98128,USA
89,90,Wilman Kala,Matti Karttunen,Keskuskatu 45,Helsinki,21240,Finland
90,91,Wolski,Zbyszek,ul. Filtrowa 68,Walla,01-012,Poland

In [15]:
customer_data.shape

(91, 7)

In [20]:
#using iloc selecting first five rows and all columns
customer_data.iloc[0:5,:]

,CustomerID,CustomerName,ContactName,Address,City,PostalCode,Country
0,1,Alfreds Futterkiste,Maria Anders,Obere Str. 57,Berlin,12209,Germany
1,2,Ana Trujillo Emparedados y helados,Ana Trujillo,Avda. de la Constitución 2222,México D.F.,05021,Mexico
2,3,Antonio Moreno Taquería,Antonio Moreno,Mataderos 2312,México D.F.,05023,Mexico
3,4,Around the Horn,Thomas Hardy,120 Hanover Sq.,London,WA1 1DP,UK
4,5,Berglunds snabbköp,Christina Berglund,Berguvsvägen 8,Luleå,S-958 22,Sweden

In [25]:
#using iloc selecting first five rows and first and second columns
customer_data.iloc[0:5,0:2]

  CustomerID                         CustomerName
0          1                  Alfreds Futterkiste
1         2   Ana Trujillo Emparedados y helados
2         3              Antonio Moreno Taquería
3         4                      Around the Horn
4         5                   Berglunds snabbköp

In [28]:
customer_data.loc[0:5,["CustomerID","CustomerName"]]

  CustomerID                         CustomerName
0          1                  Alfreds Futterkiste
1         2   Ana Trujillo Emparedados y helados
2         3              Antonio Moreno Taquería
3         4                      Around the Horn
4         5                   Berglunds snabbköp
5         6              Blauer See Delikatessen

In [31]:
customer_data[["CustomerID","CustomerName"]]

   CustomerID                           CustomerName
0           1                    Alfreds Futterkiste
1          2     Ana Trujillo Emparedados y helados
2          3                Antonio Moreno Taquería
3          4                        Around the Horn
4          5                     Berglunds snabbköp
5          6                Blauer See Delikatessen
6          7                   Blondel père et fils
7          8              Bólido Comidas preparadas
8          9                               Bon app'
9         10                 Bottom-Dollar Marketse
10        11                          B's Beverages
11        12             Cactus Comidas para llevar
12        13             Centro comercial Moctezuma
13        14                      Chop-suey Chinese
14        15                       Comércio Mineiro
15        16                  Consolidated Holdings
16        17              Drachenblut Delikatessend
17        18                        Du monde entier
18        19                     Eastern Connection
19        20                           Ernst Handel
20        21                     Familia Arquibaldo
21        22   FISSA Fabrica Inter. Salchichas S.A.
22        23                      Folies gourmandes
23        24                         Folk och fä HB
24        25                         Frankenversand
25        26                    France restauration
26        27                         Franchi S.p.A.
27        28         Furia Bacalhau e Frutos do Mar
28        29                 Galería del gastrónomo
29        30                    Godos Cocina Típica
..        ...                                    ...
61        62                          Queen Cozinha
62        63                             QUICK-Stop
63        64                          Rancho grande
64        65             Rattlesnake Canyon Grocery
65        66                     Reggiani Caseifici
66        67                     Ricardo Adocicados
67        68                     Richter Supermarkt
68        69                       Romero y tomillo
69        70                          Santé Gourmet
70        71                     Save-a-lot Markets
71        72                     Seven Seas Imports
72        73                          Simons bistro
73        74                   Spécialités du monde
74        75                  Split Rail Beer & Ale
75        76                       Suprêmes délices
76        77                         The Big Cheese
77        78                        The Cracker Box
78        79                     Toms Spezialitäten
79        80                    Tortuga Restaurante
80        81                 Tradição Hipermercados
81        82      Trail's Head Gourmet Provisioners
82        83                           Vaffeljernet
83        84                   Victuailles en stock
84        85              Vins et alcools Chevalier
85        86                      Die Wandernde Kuh
86        87                         Wartian Herkku
87        88                 Wellington Importadora
88        89                   White Clover Markets
89        90                            Wilman Kala
90        91                                 Wolski

[91 rows x 2 columns]

In [34]:
type(customer_data["Country"])

pandas.core.series.Series

In [35]:
frame = pd.DataFrame(
    [
        [1,2],
        ["Boris Yeltsin", "Mikhail Gorbachev"]
    ],
    index=["row1", "row2"],
    columns=["column1", "column2"]
)
frame

            column1            column2
row1              1                  2
row2  Boris Yeltsin  Mikhail Gorbachev

In [36]:
customer_data["Country"].head()

0    Germany
1     Mexico
2     Mexico
3         UK
4     Sweden
Name: Country, dtype: object

In [5]:
customer_data["CustomerID"].count()
# min max mean median std corr

91

In [6]:
customer_data.describe()

,CustomerID,CustomerName,ContactName,Address,City,PostalCode,Country
count,91,91,91,91,91,90,91
unique,91,91,91,91,69,86,21
top,33,Blondel père et fils,Pedro Afonso,"C/ Araquil, 67",London,1010,USA
freq,1,1,1,1,6,3,13

In [19]:
customer_data[customer_data['PostalCode']=='USA']

Empty DataFrame
Columns: [CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country]
Index: []

In [21]:
customer_data.sort_values('Country')

,CustomerID,CustomerName,ContactName,Address,City,PostalCode,Country
53,54,Océano Atlántico Ltda.,Yvonne Moncada,Ing. Gustavo Moncada 8585 Piso 20-A,Buenos Aires,1010,Argentina
63,64,Rancho grande,Sergio Gutiérrez,Av. del Libertador 900,Buenos Aires,1010,Argentina
11,12,Cactus Comidas para llevar,Patricio Simpson,Cerrito 333,Buenos Aires,1010,Argentina
19,20,Ernst Handel,Roland Mendel,Kirchgasse 6,Graz,8010,Austria
58,59,Piccolo und mehr,Georg Pipps,Geislweg 14,Salzburg,5020,Austria
75,76,Suprêmes délices,Pascale Cartrain,"Boulevard Tirou, 255",Charleroi,B-6000,Belgium
49,50,Maison Dewey,Catherine Dewey,Rue Joseph-Bens 532,Bruxelles,B-1180,Belgium
33,34,Hanari Carnes,Mario Pontes,"Rua do Paço, 67",Rio de Janeiro,05454-876,Brazil
66,67,Ricardo Adocicados,Janete Limeira,"Av. Copacabana, 267",Rio de Janeiro,02389-890,Brazil
30,31,Gourmet Lanchonetes,André Fonseca,"Av. Brasil, 442",Campinas,04876-786,Brazil
61,62,Queen Cozinha,Lúcia Carvalho,"Alameda dos Canàrios, 891",São Paulo,05487-020,Brazil
60,61,Que Delícia,Bernardo Batista,"Rua da Panificadora, 12",Rio de Janeiro,02389-673,Brazil
20,21,Familia Arquibaldo,Aria Cruz,"Rua Orós, 92",São Paulo,05442-030,Brazil
14,15,Comércio Mineiro,Pedro Afonso,"Av. dos Lusíadas, 23",São Paulo,05432-043,Brazil
80,81,Tradição Hipermercados,Anabela Domingues,"Av. Inês de Castro, 414",São Paulo,05634-030,Brazil
87,88,Wellington Importadora,Paula Parente,"Rua do Mercado, 12",Resende,08737-363,Brazil
9,10,Bottom-Dollar Marketse,Elizabeth Lincoln,23 Tsawassen Blvd.,Tsawassen,T2F 8M4,Canada
50,51,Mère Paillarde,Jean Fresnière,43 rue St. Laurent,Montréal,H1J 1C3,Canada
41,42,Laughing Bacchus Wine Cellars,Yoshi Tannamuri,1900 Oak St.,Vancouver,V3F 2K1,Canada
82,83,Vaffeljernet,Palle Ibsen,Smagsløget 45,Århus,8200,Denmark
72,73,Simons bistro,Jytte Petersen,Vinbæltet 34,København,1734,Denmark
89,90,Wilman Kala,Matti Karttunen,Keskuskatu 45,Helsinki,21240,Finland
86,87,Wartian Herkku,Pirkko Koskitalo,Torikatu 38,Oulu,90110,Finland
39,40,La corne d'abondance,Daniel Tonini,"67, avenue de l'Europe",Versailles,78000,France
56,57,Paris spécialités,Marie Bertrand,"265, boulevard Charonne",Paris,75012,France
40,41,La maison d'Asie,Annette Roulet,1 rue Alsace-Lorraine,Toulouse,31000,France
73,74,Spécialités du monde,Dominique Perrier,"25, rue Lauriston",Paris,75016,France
25,26,France restauration,Carine Schmitt,"54, rue Royale",Nantes,44000,France
22,23,Folies gourmandes,Martine Rancé,"184, chaussée de Tournai",Lille,59000,France
6,7,Blondel père et fils,Frédérique Citeaux,"24, place Kléber",Strasbourg,67000,France
...,...,...,...,...,...,...,...
68,69,Romero y tomillo,Alejandra Camino,"Gran Vía, 1",Madrid,28001,Spain
29,30,Godos Cocina Típica,José Pedro Freyre,"C/ Romero, 33",Sevilla,41101,Spain
4,5,Berglunds snabbköp,Christina Berglund,Berguvsvägen 8,Luleå,S-958 22,Sweden
23,24,Folk och fä HB,Maria Larsson,Åkergatan 24,Bräcke,S-844 67,Sweden
13,14,Chop-suey Chinese,Yang Wang,Hauptstr. 29,Bern,3012,Switzerland
67,68,Richter Supermarkt,Michael Holz,Grenzacherweg 237,Genève,1203,Switzerland
3,4,Around the Horn,Thomas Hardy,120 Hanover Sq.,London,WA1 1DP,UK
10,11,B's Beverages,Victoria Ashworth,Fauntleroy Circus,London,EC2 5NT,UK
15,16,Consolidated Holdings,Elizabeth Brown,Berkeley Gardens 12 Brewery,London,WX1 6LT,UK
18,19,Eastern Connection,Ann Devon,35 King George,London,WX3 6FW,UK
52,53,North/South,Simon Crowther,South House 300 Queensbridge,London,SW7 1RZ,UK
37,38,Island Trading,Helen Bennett,Garden House Crowther Way,Cowes,PO31 7PJ,UK
71,72,Seven Seas Imports,Hari Kumar,90 Wadhurst Rd.,London,OX15 4NB,UK
70,71,Save-a-lot Markets,Jose Pavarotti,187 Suffolk Ln.,Boise,83720,USA
88,89,White Clover Markets,Karl Jablonski,305 - 14th Ave. S. Suite 3B,Seattle,98128,USA
47,48,Lonesome Pine Restaurant,Fran Wilson,89 Chiaroscuro Rd.,Portland,97219,USA
44,45,Let's Stop N Shop,Jaime Yorres,87 Polk St. Suite 5,San Francisco,94117,USA
42,43,Lazy K Kountry Store,John Steel,12 Orchestra Terrace,Walla Walla,99362,USA
35,36,Hungry Coyote Import Store,Yoshi Latimer,City Center Plaza 516 Main St.,Elgin,97827,USA
81,82,Trail's Head Gourmet Provisioners,Helvetius Nagy,722 DaVinci Blvd.,Kirkland,98034,USA
77,78,The Cracker Box,Liu Wong,55 Grizzly Peak Rd.,Butte,59801,USA
76,77,The Big Cheese,Liz Nixon,89 Jefferson Way Suite 2,Portland,97201,USA
31,32,Great Lakes Food Market,Howard Snyder,2732 Baker Blvd.,Eugene,97403,USA
74,75,Split Rail Beer & Ale,Art Braunschweiger,P.O. Box 555,Lander,82520,USA
54,55,Old World Delicatessen,Rene Phillips,2743 Bering St.,Anchorage,99508,USA
64,65,Rattlesnake Canyon Grocery,Paula Wilson,2817 Milton Dr.,Albuquerque,87110,USA
34,35,HILARIÓN-Abastos,Carlos Hernández,Carrera 22 con Ave. Carlos Soublette #8-35,San Cristóbal,5022,Venezuela
32,33,GROSELLA-Restaurante,Manuel Pereira,5ª Ave. Los Palos Grandes,Caracas,1081,Venezuela
46,47,LINO-Delicateses,Felipe Izquierdo,Ave. 5 de Mayo Porlamar,I. de Margarita,4980,Venezuela
45,46,LILA-Supermercado,Carlos González,Carrera 52 con Ave. Bolívar #65-98 Llano Largo,Barquisimeto,3508,Venezuela